<a href="https://colab.research.google.com/github/hsargoli/MyWorks/blob/main/algorithms_and_simpleCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
# CHANGE CASH
'''Create a program that helps a cashier give adequate change to customers.
The program should return the amount of coins for the customer’s change.'''
import numpy as np
import math

def chashier(rv):
  money = rv
  coins = [500, 100, 20, 5, 2, 1]
  d = len(coins)
  while money > 0: 
    for k in range(d): # 
      ik = int(math.floor(int(money)/int(coins[k])))

      money = money - coins[k] * ik
      print(f'need {ik} X {coins[k]}$','\t',f' rest {money}')
      if money == 0:
        break
chashier(44)

need 0 X 500$ 	  rest 44
need 0 X 100$ 	  rest 44
need 2 X 20$ 	  rest 4
need 0 X 5$ 	  rest 4
need 2 X 2$ 	  rest 0


In [118]:
# reverse Sum
a = [3,4,0]
b = [0,9,1]
c = ""
d = ""
for i in range(len(a)-1,-1,-1):
 c+=str(a[i])
 d+=str(b[i])
print(c, d, sep=' ')
z = int(c)+int(d)
z

043 190


233

In [119]:
# roman integer
# ------------------
def roman(a):   #input must string
  d=0
  b={'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}
  for i in range(len(a)):
    c = b[a[i]]
    d += c
  return d
roman('DXII')

512

In [113]:
# Palindrome Linked List
# ------------------
def pll(a):
  b = a[-1::-1]
  print(b)
  return a == b
pll([1,2,2,1])

[1, 2, 2, 1]


True

In [120]:
# Ransom Note return True if a can created from b
# ------------------
def Rn(a,b):
  c, d=list(a), list(b)
  e = len(c)
  f = 0
  for i in c:
    if i in d:
      f += 1
  return f == e
Rn('aawe','aabgw easdr')

TypeError: ignored

In [116]:
# Longest Substring Without Repeating Characters
# ------------------
def lswrc(a):
  d = []
  c=''
  for i in range(len(a)):
    if a[i] not in c:
      c += a[i]
      # for visualize :  print('-- ',c)
    else:
      print(c)
      d.append(c)
      c = ''
      c += a[i]
    if i == len(a)-1:
      d.append(c)
  return d
lswrc('abcd abcder rgtewroas;jcosan')


abcd 
abcder 
rgtew
roas;jc
['geasw']


In [103]:
# Number of Pairs of Interchangeable Rectangles
# how many unique aspect ratio rectangle we can create from given array 
# ------------------
rectangles = [[4,8],[3,6],[10,20],[14,32],[28,64]]
def rec_pair(a):
  d = 0
  for i,j in enumerate(a):
    b = j[0]/j[1] 
    for k in range(len(a),1 + i,-1):
      if a[k-1][0]/a[k-1][1] == b:
        d +=1
  return d
rec_pair(rectangles)

4

In [60]:
# pariy of binary words
'''
he parity of a binary word is 1 if the word contains an 
odd number of 1s and 0 if it contains an even number of ones.
More generally, any linear operation on a vector of bits is given
by multiplication by a binary matrix, where arithmetic is carried out mod 2
'''
from collections import Counter 
h='10110001'
c=Counter(h)
def parity(x):
  b=Counter(x)
  c=0 if b['1']% 2 ==0 else 1
  return c
parity(h)

0

In [86]:
# In Python, how do DECORATORS work?
# It's like wrapping our function in another function
# define decorator functions ->
# --------------------------------------------------------
def deco(func): # it takes Function as its parameter
  print('im decorator')
  def wrapp(*args,**kwargs):
    print('function operates:')
    begin = time.time()
    func(*args, **kwargs)
    end = time.time()
    print("Total time taken in : ", func.__name__, end - begin)
    return func(*args,**kwargs)
  return wrapp
def sss():
  print(' hiii')
sss = deco(sss)
sss()
# --------------------------------------------------------
def create_adder(x):
    def adder(y):
        return x+y
 
    return adder
add_15 = create_adder(15)
print(add_15(10))
# --------------------------------------------------------
@deco
def aaa(a):
  return a + 1
aaa(9)
# --------------------------------------------------------
def calculate_time(func):
     
    # added arguments inside the inner1,
    # if function takes any arguments,
    # can be added like this.
    def inner1(*args, **kwargs):
 
        # storing time before function execution
        begin = time.time()
         
        func(*args, **kwargs)
 
        # storing time after function execution
        end = time.time()
        print("Total time taken in : ", func.__name__, end - begin)
 
    return inner1


im decorator
function operates:
 hiii
Total time taken in :  sss 2.6941299438476562e-05
 hiii
25
im decorator
function operates:
Total time taken in :  aaa 1.430511474609375e-06


In [89]:
#===============================
# reduce  function    =========
# ==============================
'''
The reduce(fun,seq) function is used to apply a particular function passed in 
its argument to all of the list elements mentioned in the sequence passed along.
This function is defined in “functools” module.
'''
from functools import reduce
a=[1,4,2]
print(reduce(lambda x,y : x/y,a))
reduce(lambda x,y: x if x<y else y,[5,1,2,3,7]) # return min


0.125


1

In [93]:
#===============================
# RECURSION   ==================
# ==============================
def recursive_factorial(n):  
   if n == 1:  
       return n  
   else:
       return n * recursive_factorial(n-1) 
def fibo(n):
  if n <= 1:
    return 1
  else:
    return fibo(n-1) + fibo(n-2)
#===============================
for i in range(8):
  print(f'index {i}   fibo number: {fibo(i)}, )')
print('factoriel',recursive_factorial(5))

index 0   fibo number: 1, )
index 1   fibo number: 1, )
index 2   fibo number: 2, )
index 3   fibo number: 3, )
index 4   fibo number: 5, )
index 5   fibo number: 8, )
index 6   fibo number: 13, )
index 7   fibo number: 21, )
factoriel 120


In [ ]:
# -----------------------------------------------------
#min sum                            -------------------
# -----------------------------------------------------
data = [3,5,1,6,10,3,8,4]
dataa= np.random.randint(2,10,50)

# -----------------------------------------------
def sm(dat):
  a=0
  for i in dat:
    a += i
  return a

def miin(dat):
  d=dat[0]
  for i in range(len(dat)-1,-1,-1):
    a=dat[i];b=dat[i-1]
    if a <= b:
      if a <=d :
        d = a 
  return d
# -----------------------------------------------
print('sum data',sm(data),'\tmin ',miin(dataa))

sum data 40 	min  2


In [ ]:
# ooooooooooooooooo ooooooooooooooooooooooooooooooooooo
# binary search                     -------------------
# -----------------------------------------------------
import numpy as np
data = np.arange(20,2100,3)
from time import time
sss=time()
b=[]
def BS(da,valu):
  data=np.copy(da)
  a = int(len(da)/2)
  #print(a,da)
  if valu > da[a]:
    b.append(a)
    for i in range(a):
      da=np.delete(da,0)
    BS(da,valu)
  elif valu < da[a]:
    for i in range(len(da),-a+len(da),-1):
      da=np.delete(da,-1)
    BS(da,valu)
  elif valu == da[a]:
    print('succes')
    b.append(a)
    c = sum(b)
    print('-we need the -',data[a],'== founded index ==',c)

if __name__ == '__main__':
  v=BS(data,1001)
  print(time()-sss)

succes
-we need - 1001 == founded index == 327
0.009794473648071289


In [ ]:
# ----------------------------------------------------
# my sort algorithm        - - - > sg < -------------------
#-----------------------------------------------------
data0=np.random.randint(1,100,500)
print(data0)
st= time.time()
def tek(data):
  for i in range(len(data)-1,0,-1):
    if data[i] < data[i-1]:
      data[i] , data[i-1]=data[i-1], data[i]
  return data
def do(data):
  t=0
  while t <  len(data):
    data=tek(data)
    t +=1
  return data

print(do(data0))
el=time.time() - st
el

[88 73 85 88 21 47 51 21 76 84  7 61 57 42 87 40 25 40 14 44 97 12  3 61
 60 52 71 92 91 99 51 47 66 18 52  1 77 11  4 32 61 42 68 62 94 97 50  8
  4 58 82 86 55 90 19 30 14 84 52 45 87 91 62 59 42  7 53  8 44 57 16 87
 22  9 91  7 18 60 13  6 59 72 73 17 61  5 89 85 41 78 96 99 76 96 35 23
 19  2 31 74 80  4 71 51 95 59 92 10 77 80 48 16 60 63  5 58 35 78 82  3
 31 52 81 40 41 72 38 76 49 21 11 97 66  9 86 30 12 21 63 75  5 16 91 96
 60 73 27  8 50 59 85 30 68 33 27 94 74 71 85 60 40 33  4 89 67 23 81 10
 92 70 85 49 68 32 88 27 49 84 17 38 24 28 50 94 75 41 92 39 34 29 13 56
 58 48 32 93 66 79 65 36 46 23 18 62 97 52 40 25 80 90 91 79 53 86 21 61
 17 30 14 22 32  4 16 37 11 78 32 24 86 29 36  8 30 18 99  5 96 27 42 92
 91 61 58 72 33 55 70 40 77 96  5 77 27 11  3 48 24 39 56 71 90  2 68 86
 51 13 20  3 21 65  8 91 78 80 54 55 71 85 17 58 81 26 93 62 86 52 30 84
 24 64 66 45 83  3 28 33 64 61 18 30 27 99 41  3 29  9 90  7 83 22 21  8
  1 64 79 74 79 32 92 89 63 77 40 75 52 27 87 72 43

0.0853426456451416

In [45]:
#===============================
# buuble sort
# ==============================
import numpy as np
import copy
data0 = np.random.randint(1,100,5)
import time
st=time.time()
list = copy.copy(data0)
for iter_num in range(len(list)-1,0,-1):
      for idx in range(iter_num):
         if list[idx]>list[idx+1]:
            temp = list[idx]
            list[idx] = list[idx+1]
            list[idx+1] = temp
      print(list,temp)

print(f'from this {data0} \tto this {list}')
print(any(sorted(data0) == list))
el=time.time()-st
print(el)

[46 90 87 11 93] 93
[46 87 11 90 93] 90
[46 11 87 90 93] 87
[11 46 87 90 93] 46
from this [90 46 93 87 11] 	to this [11 46 87 90 93]
True
0.0051038265228271484


In [71]:
import numpy as np 
q=np.array([[1,2,3],[0,0,6],[7,8,9]])
np.linalg.det(q)
np.linalg.matrix_rank(q)

3

In [78]:
#A naive recursive implementation of 0-1 Knapsack Problem 
# Returns the maximum value that can be put in a knapsack of 
# This code is contributed by Nikhil Kumar Singh
# capacity W 
def knapSack(W , wt , val , n): 
    i=0
    i +=1
    # Base Case 
    if n == 0 or W == 0 : 
        return 0
  
    # If weight of the nth item is more than Knapsack of capacity 
    # W, then this item cannot be included in the optimal solution 
    if (wt[n-1] > W): 
        return knapSack(W , wt , val , n-1) 
  
    # return the maximum of two cases: 
    # (1) nth item included 
    # (2) not included 
    else: 
        return max(val[n-1] + knapSack(W-wt[n-1] , wt , val , n-1), 
                   knapSack(W , wt , val , n-1)) 
# end of function knapSack 
  
# To test above function 
val = [60, 100, 120, 140] 
wt = [10, 60, 40, 60] 
W = 130
n = len(val) 
print(len(val))
print (knapSack(W , wt , val , n))
  


4
320


In [ ]:
# Python program for implementation of MergeSort
def mergeSort(arr):
	if len(arr) > 1:

		# Finding the mid of the array
		mid = len(arr)//2

		# Dividing the array elements
		L = arr[:mid]

		# into 2 halves
		R = arr[mid:]

		# Sorting the first half
		mergeSort(L)


		# Sorting the second half
		mergeSort(R)
		i = j = k = 0
		print('\n---',L,R,sep=' ',end='---\n')
		# Copy data to temp arrays L[] and R[]
		while i < len(L) and j < len(R):
			if L[i] < R[j]:
				print('left',L[i],R[j])
				arr[k] = L[i]
				i += 1
			else:
				print('right',R[j],L[i])
				arr[k] = R[j]
				j += 1
			k += 1
		print(arr,'k',k,i,j,sep='  ')
		# Checking if any element was left
		while i < len(L):
			
			arr[k] = L[i]
			i += 1
			k += 1

		while j < len(R):
			arr[k] = R[j]
			j += 1
			k += 1
		print(arr,'k',k)

# Code to print the list


def printList(arr):
	for i in range(len(arr)):
		print(arr[i], end=" ")
	print()


# Driver Code
if __name__ == '__main__':
	arr = [12, 11, 13, 5, 10, 7]
	print("Given array is", end="\n")
	printList(arr)
	mergeSort(arr)
	print("Sorted array is: ", end="\n")
	printList(arr)

# This code is contributed by Mayank Khanna


Given array is
12 11 13 5 10 7 

--- [11] [13]---
left 11 13
[11, 13]  k  1  1  0
[11, 13] k 2

--- [12] [11, 13]---
right 11 12
left 12 13
[11, 12, 13]  k  2  1  1
[11, 12, 13] k 3

--- [10] [7]---
right 7 10
[7, 7]  k  1  0  1
[7, 10] k 2

--- [5] [7, 10]---
left 5 7
[5, 10, 7]  k  1  1  0
[5, 7, 10] k 3

--- [11, 12, 13] [5, 7, 10]---
right 5 11
right 7 11
right 10 11
[5, 7, 10, 5, 10, 7]  k  3  0  3
[5, 7, 10, 11, 12, 13] k 6
Sorted array is: 
5 7 10 11 12 13 


In [ ]:
# Python program for KMP Algorithm
# This code is contributed by Bhavya Jain

'''
KMP Algorithm for Pattern Searching
'''
def KMPSearch(pat, txt):
	M = len(pat)
	N = len(txt)

	# create lps[] that will hold the longest prefix suffix
	# values for pattern
	lps = [0]*M
	j = 0 # index for pat[]

	# Preprocess the pattern (calculate lps[] array)
	computeLPSArray(pat, M, lps)

	i = 0 # index for txt[]
	while i < N:
		if pat[j] == txt[i]:
			i += 1
			j += 1

		if j == M:
			print ("Found pattern at index " + str(i-j))
			j = lps[j-1]

		# mismatch after j matches
		elif i < N and pat[j] != txt[i]:
			# Do not match lps[0..lps[j-1]] characters,
			# they will match anyway
			if j != 0:
				j = lps[j-1]
			else:
				i += 1

def computeLPSArray(pat, M, lps):
	len = 0 # length of the previous longest prefix suffix

	lps[0] # lps[0] is always 0
	i = 1

	# the loop calculates lps[i] for i = 1 to M-1
	while i < M:
		if pat[i]== pat[len]:
			len += 1
			lps[i] = len
			i += 1
		else:
			# This is tricky. Consider the example.
			# AAACAAAA and i = 7. The idea is similar
			# to search step.
			if len != 0:
				len = lps[len-1]

				# Also, note that we do not increment i here
			else:
				lps[i] = 0
				i += 1

txt = "ABABDABACDABABCABAB"
pat = "ABAB"
KMPSearch(pat, txt)



Found pattern at index 0
Found pattern at index 10
Found pattern at index 15


In [ ]:
import cProfile
#cProfile.run('do(data0)')
import random